### PR TITLE
Updates for Rails 4 and Ruby 2.0

### PR DESCRIPTION
**Pull request by fabiob**
Thanks for the tips from @daniel-rikowski on issue #59, I managed to make `delocalize` work on Rails 4 RC1.

Some tests are still not passing, though… I found 3 issues:

* Timecop does not seem to work very well on Ruby 2.0, so some tests that rely on it are failing;
* Looks like Rails 4 does not emit the "size" attribute on input tags anymore, so I had to remove those from the ActionView tests in order to make them pass;
* Some decimals are being translated to `BigDecimal` instances, which are not comparable.

Other than that, this changes should be working just fine.

### CODE REVIEW

**Comment by sobrinho** [comment]
@fabiob I'm getting an exception on rails 4.2:

```
/vagrant/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `type_cast' for class `ActiveRecord::ConnectionAdapters::Column' (NameError)
        from /vagrant/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
        from /vagrant/vendor/bundle/ruby/2.1.0/bundler/gems/delocalize-a71ba471acb3/lib/delocalize/rails_ext/active_record_rails4.rb:14:in `block in <top (required)>'
        from /vagrant/vendor/bundle/ruby/2.1.0/bundler/gems/delocalize-a71ba471acb3/lib/delocalize/rails_ext/active_record_rails4.rb:1:in `class_eval'
        from /vagrant/vendor/bundle/ruby/2.1.0/bundler/gems/delocalize-a71ba471acb3/lib/delocalize/rails_ext/active_record_rails4.rb:1:in `<top (required)>'
        from /vagrant/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /vagrant/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /vagrant/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /vagrant/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /vagrant/vendor/bundle/ruby/2.1.0/bundler/gems/delocalize-a71ba471acb3/lib/delocalize/rails_ext/active_record.rb:22:in `<top (required)>'
```

Have you already fixed that?

**Comment by clemens** [comment]
As you can see, Fabio worked with Rails 4.0 RC1 at the time – you're apparently working with Rails 4.2.1 which is quite a bit newer.

If you want to use delocalize with newer Rails versions, I suggest you use the 1-0-beta branch which offers a different approach to things and is less reliant on Rails internals. Any feedback (especially if you run into issues with it) would be much appreciated so I can finally ditch the old approach and use the new one. :)

**Comment by sobrinho** [comment]
Hey @clemens, I will give it a shot but I'm resistant to the new approach.

Integrating with strong parameters like `params.require(:foo).permit(:bar).delocalize(bar: :date)` is interesting because it seems to be on the right place but views would be a complete pain for me because my application is quite large (monolithic), it may have hundred of date, time and number fields.

What's the new approach for forms? Like this?

``` ruby
f.text_field :date, value: @object.date ? l(@object.date) : nil
f.text_field :quantity, value: number_with_precision(@object.quantity, precision: 2)
```

I'm using simple form so I can do it more magically but what about who applications use just rails?

**Comment by clemens** [comment]
Yes and no.

If you use vanilla Rails, that's how you'd do it. However, in most of my projects nowadays I use https://github.com/drapergem/draper and/or form objects (e.g. https://github.com/apotonick/reform or https://github.com/rom-rb/rom-rails/blob/master/lib/rom/rails/model/form.rb – or just roll your own variation of it). I firmly believe that stuff like localization shouldn't be done in helper methods let alone directly in the view and instead should be handled in separate objects (be it presenters, decorators, form objects or whatever).

With one of these gems in place, it should be fairly easy to write some wrapper methods and/or macro methods to integrate well with delocalize. I can, for instance, imagine coming up with a DSL that looks somewhat like this:

``` ruby
class ProductForm < Reform::Form
  include LocalizedAttributes # this would carry the class-level localize method
  localize released_on: { as: :date, format: :short }, price: { as: :currency }
end
```

**Comment by daniel-rikowski** [comment]
I've been using 1.0-beta ever since the nested forms problem was solved (#76)

Converting my old applications was indeed a pain, but I hope that this new approach makes delocalize future-proof. (Let's see about Rails 5 if that actually is true :fearful: )

I'm using Formtastic and I created custom inputs, so no problem there, too.

But I added the original `parse_localized` methods to `Numeric` and `Time` because I have some CSV importers which made heavy use of it.

Other than that I did not encouter any problems in the last 6 months.

**Comment by sobrinho** [comment]
I upgraded a small application to use the 1-0-beta and everything is working fine.

I didn't liked the form object solution because it adds a bureaucracy for something that doesn't change (every date input should use `I18n.l` and every decimal input should use `number_with_precision`) but using simple form was easy enough.

Still not sure how to deal with that for multiple applications, this behaviour will be shared across all my applications (maybe a private gem?).

Would be great to have these suggestions (form object and simple form custom input) documented on README.

Anyway :shipit:

**Comment by sobrinho** [comment]
This can be closed due to architectural changes.

About simple form, I've written a small snippet on wiki [here](https://github.com/clemens/delocalize/wiki/Using-with-simple-form).
